/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kopral.views;

import com.kopral.entity.User;
import com.kopral.impl.UserImpl;
import com.kopral.servise.UserServise;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author agung
 */
public class FormUtama extends javax.swing.JFrame {
List<User> list;
UserServise userServise;
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        userServise= new UserImpl();
        SimpleDateFormat df = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        Date date = new Date();
        jLabel1.setText(df.format(date)+"   ");
        jMenu2.setEnabled(false);
        jMenu3.setEnabled(false);
    }

    /**
     * This method is called fro= m within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menulogin = new javax.swing.JMenuItem();
        menulogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnanggota = new javax.swing.JMenuItem();
        mnkelompok = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuser = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PANEL LOGIN");

        jLabel3.setText("User Name     :");

        jLabel4.setText("Password     :");

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(txtpassword)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 25));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menulogin.setText("Login");
        menulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuloginActionPerformed(evt);
            }
        });
        jMenu1.add(menulogin);

        menulogout.setText("Logout");
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menulogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        mnanggota.setText("Anggota");
        mnanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnanggotaActionPerformed(evt);
            }
        });
        jMenu2.add(mnanggota);

        mnkelompok.setText("Kelompok");
        mnkelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnkelompokActionPerformed(evt);
            }
        });
        jMenu2.add(mnkelompok);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master Pengguna");

        mnuser.setText("Data User");
        mnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuserActionPerformed(evt);
            }
        });
        jMenu3.add(mnuser);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        jMenuItem8.setText("Lap Data Per Anggota");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Lap Data Kelompok");
        jMenu4.add(jMenuItem9);

        jMenuItem5.setText("Lap Data Per Desa");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnanggotaActionPerformed
        try {
        FormAnggota fb= new FormAnggota();
        jPanel2.add(fb);
        fb.setVisible(true);
        fb.setSize(jPanel2.getSize());    
        } catch (Exception e) {
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_mnanggotaActionPerformed

    private void mnkelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkelompokActionPerformed
        try {
        FormKelompok fb= new FormKelompok();
        jPanel2.add(fb);
        fb.setVisible(true);
        fb.setSize(jPanel2.getSize());    
        } catch (Exception e) {
        }
                  // TODO add your handling code here:
    }//GEN-LAST:event_mnkelompokActionPerformed

    private void mnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuserActionPerformed
         try {
        FormUsers fb= new FormUsers();
        jPanel2.add(fb);
        fb.setVisible(true);
        fb.setSize(jPanel2.getSize());    
        } catch (Exception e) {
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_mnuserActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.login();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuloginActionPerformed
jDialog1.setSize(50, 30);
jDialog1.setLocationRelativeTo(null);
jDialog1.setVisible(true);// TODO add your handling code here:
txtusername.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_menuloginActionPerformed

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menulogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        try {
//            UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
//        } catch (Exception e) {
//        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                try {
	    // Set System L&F
                    UIManager.setLookAndFeel(
                        UIManager.getSystemLookAndFeelClassName());
                    }
                    catch (UnsupportedLookAndFeelException e) {
                       // handle exception
                    }
                    catch (ClassNotFoundException e) {
                       // handle exception
                    }
                    catch (InstantiationException e) {
                       // handle exception
                    }
                    catch (IllegalAccessException e) {
                       // handle exception
                    }
                
                FormUtama f = new FormUtama();
                f.setExtendedState(JFrame.MAXIMIZED_BOTH);
                f.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menulogin;
    private javax.swing.JMenuItem menulogout;
    private javax.swing.JMenuItem mnanggota;
    private javax.swing.JMenuItem mnkelompok;
    private javax.swing.JMenuItem mnuser;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

boolean ceklogin(String user,String pass) throws SQLException{
    
    boolean hasil = false;
        try {
            User s=new User();
            s = userServise.getbyuser(user);
            if(user.equals(s.getUsername())&&pass.equals(s.getPassword())){
            hasil=true;
            }else{
                hasil=false;
            }
        } catch (SQLException e) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null,e);
        }
     return hasil;
    }    

public void logout(){
        super.dispose();
        FormUtama fl= new FormUtama();
        fl.setVisible(true);
    }

public void login(){
    User s = new User();
    try {
            if (ceklogin(txtusername.getText(), txtpassword.getText())) {
                txtusername.setText("");
                txtpassword.setText("");
                //MenuFile.setEnabled(false);
                menulogout.setEnabled(true);
                //this.setTitle("admin_nama : " + p.getNamapetugas() + " : " + p.getNamapetugas() + " Sistem Informasi Perpustakaan");
setTitle("Nama Petugas : " + s.getNama());
//jLabel7.setEnabled(true);
                String ss=s.getKode();
                jDialog1.setVisible(false);
                jMenu2.setEnabled(true);
                jMenu3.setEnabled(false);
            }
            // TODO add your handling code here:
        }catch (SQLException e) {
        
        }
      txtusername.setText("");
      txtpassword.setText("");
}
}
